formated_ppi: "work_folder/formated/bait_prey_publications.csv"
cell_line_ppis: "data/CL_annotated_bait_prey.csv"

remove_single_publications: True
min_total_tests: 30
min_total_observed: 4
part_or_difference_cutoff: 50
pseudo_n: 1
HCL_frac: 0.8
negatome_tested_threshold: 4
id_pattern: "gene_name"
prey_n_MCMC_batch: 2000
MCMC_workers: 45
batch_per_write: 1000
mcmc_samples: 4000
mcmc_burin: 4000

localisation_file: "data/localisation/gene_to_location.csv"

selected_cell_lines:
  - "CVCL_0063"
  - "CVCL_0291"
  - "CVCL_0030"

ms:
  - "MI-0006"
  - "MI-0007"
  - "MI-0096"
  - "MI-0676"
  - "MI-1314"

y2h:
  - "MI-0397" # (two hybrid array)
  - "MI-1112" # (two hybrid prey pooling approach)
  - "MI-0398" # (two hybrid pooling approach)
  - "MI-0018" # (two hybrid)
  - "MI-0399" # (two hybrid fragment pooling approach) NOTE: One-to-one
  - "MI-1356" # (validated two hybrid)
  - "MI-2215" # (barcode fusion genetics two hybrid)
  - "MI-1113" # (two hybrid bait and prey pooling approach)