pid_context:
    "data/pubid_cell_line/pubtator/cellline2pubtator3_human.csv"


excluded_pubmedIDs:
    - "33961781" # BioPlex

methods:
    MI-0006: "MS" # (anti bait coimmunoprecipitation)
    MI-0007: "MS" # (anti tag coimmunoprecipitation)
    MI-1112: "Y2H-pooling" # (two hybrid prey pooling approach)
    MI-1314: "MS" # (proximity-dependent biotin identification)
    MI-0096: "MS" # (pull down)
    MI-0004: "MS" # (affinity chromatography technology)
    MI-0019: "MS"# (coimmunoprecipitation)

cell_lines:
    CVCL_0030: # HeLa
        pod: "data/geneGroups/relative_freq_wide_selected_N04547_M07444.csv"
    CVCL_0045: # HEK293
        pod:
    CVCL_0063: # HEK293T
        pod:
    CVCL_0598: # MCF-10 (A/F ?, pubtator is inconsistent)
        pod:
    CVCL_0042: # U2OS
        pod:
