methods:
    MI-0007: # (anti tag coimmunoprecipitation)
    MI-0397: # (two hybrid array)
    MI-1112: # (two hybrid prey pooling approach)
    MI-1314: # (proximity-dependent biotin identification)
    MI-0006: # (anti bait coimmunoprecipitation)
    MI-0096: # (pull down)
    MI-0676: # (tandem affinity purification)
    MI-0398: # (two hybrid pooling approach)
    MI-0018: # (two hybrid)
    MI-0030: # (cross-linking study)
    MI-0004: # (affinity chromatography technology)
    MI-0399: # (two hybrid fragment pooling approach) NOTE: One-to-one
    MI-0112: # (ubiquitin reconstruction)
    MI-0729: # (luminescence based mammalian interactome mapping)
    MI-0081: # (peptide array)
    MI-0019: # (coimmunoprecipitation)
    MI-0107: # (surface plasmon resonance)
    MI-0089: # (protein array)
    MI-0034: # (display technology)
    MI-1356: # (validated two hybrid)
    MI-0084: # (phage display)
    MI-2215: # (barcode fusion genetics two hybrid)
    MI-1113: # (two hybrid bait and prey pooling approach)
    MI-2289: # (virotrap)
    MI-0231: # (mammalian protein protein interaction trap)
    MI-0411: # (enzyme linked immunosorbent assay)
    MI-0049: # (filter binding)
    MI-0047: # (far western blotting)
    MI-0029: # (cosedimentation through density gradient)
    MI-0809: # (bimolecular fluorescence complementation)
    MI-1313: # (proximity labelling technology)
    MI-0097: # (reverse ras recruitment system)
    MI-0900: # (p8 filamentous phage display)
    MI-0892: # (solid phase assay)
    MI-0402: # (chromatin immunoprecipitation assay)
    MI-0405: # (competition binding)
    MI-0678: # (antibody array)
    MI-0008: # (array technology)
    MI-0969: # (bio-layer interferometry)
    MI-0065: # (isothermal titration calorimetry)
    MI-0090: # (protein complementation assay)
    MI-0099: # (scintillation proximity assay)
    MI-0728: # (gal4 vp16 complementation)
    MI-0727: # (lexa b52 complementation)
    MI-0054: # (fluorescence-activated cell sorting)
    MI-0588: # (three hybrid)
    MI-0071: # (molecular sieving)
    MI-0428: # (imaging technique)
    MI-0663: # (confocal microscopy)
    MI-0416: # (fluorescence microscopy)
    MI-0400: # (affinity technology)
    MI-0010: # (beta galactosidase complementation)
    MI-0369: # (lex-a dimerization assay)
    MI-0011: # (beta lactamase complementation)
    MI-0440: # (saturation binding)
    MI-0655: # (lambda repressor two hybrid)
    MI-0401: # (biochemical)
    MI-0424: # (protein kinase assay)
    MI-0858: # (immunodepleted coimmunoprecipitation)
    MI-0091: # (chromatography technology)


cell_lines:
    HeLa:
        pod: "data/geneGroups/relative_freq_wide_selected_N04547_M07444.csv"